Repository gisce/libCNMC, pull requests merged in 2018-05, with the labels that each got.

#320 Improve the F9 Generation
  libcnmc/cir_4_2015/F9.py
  libcnmc/utils.py
Labels: enhancement, to be merged

#323 Switch fields municipi and provincia
  libcnmc/cir_4_2015/F1.py
Labels: error

#325 Compare with float instead of str
  libcnmc/cir_4_2015/F1.py
Labels: error

#326 Don't include RE polisses on energy of F11
  libcnmc/cir_4_2015/F11.py
Labels: WIP, enhancement

#327 Fix "codi ine municipi" on F1 4/2015
  libcnmc/cir_4_2015/F1.py
Labels: error, to be merged

#319 Add extended option to 4666
  libcnmc/cli_4666.py
  libcnmc/res_4666/CTS.py
  libcnmc/res_4666/FIA.py
  libcnmc/res_4666/LAT.py
  libcnmc/res_4666/LBT.py
  libcnmc/res_4666/POS.py
Labels: enhancement, to be merged

#324 Imp f12bis f13c f15 42015
  libcnmc/cir_4_2015/F12bis.py
  libcnmc/cir_4_2015/F13C.py
  libcnmc/cir_4_2015/F15.py
Labels: enhancement

#329 Use the same criteria on F1bis than F1 for baja
  libcnmc/cir_4_2015/F1bis.py
Labels: error

#334 Rename connection variable
  libcnmc/utils.py
Labels: enhancement

#331 Fix identation of utils
  libcnmc/utils.py
Labels: enhancement

#333 Add exception message to raise
  libcnmc/cir_4_2015/create_celles.py
Labels: enhancement

#332 Add f1 docstrings
  libcnmc/cir_4_2015/F1.py
Labels: enhancement

#335 Usar el campo potencia adscrita en lugar del campo del boletin
  libcnmc/cir_4_2015/F1.py
Labels: enhancement

#337 Add requirements files to setup file
  MANIFIEST.in
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: enhancement, to be merged

#336 Improve F1 and F1bis
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F1bis.py
Labels: enhancement, error, to be merged

#339 Añadir template para la pull request
  .github/pull_request_template.md
Labels: enhancement

#338 Arreglar campo zona del CT cuando el CT esta de baja
  libcnmc/cir_4_2015/F1.py
Labels: error, to be merged

#340 Arreglar instalacion de paquete
  MANIFEST.in
Labels: error

#341 Añadir opcion para poder escojer si solo se quiere que aparezcan elementos de fiabilidad en el F12
  libcnmc/cir_4_2015/F12bis.py
  libcnmc/cli_4_2015.py
Labels: enhancement

#343 Mejorar la generacion del fichero F15 incluyendo posiciones
  libcnmc/cir_4_2015/F15.py
  libcnmc/cir_4_2015/__init__.py
  libcnmc/cli_4_2015.py
  libcnmc/utils.py
Labels: enhancement, to be merged
