Repository gisce/libCNMC, pull requests merged in 2018-06, with the labels that each got.

#344 Arreglar unidades de tension
  libcnmc/cir_4_2015/F15.py
Labels: error, to be merged

#345 Improve F15 propietari
  libcnmc/cir_4_2015/F15.py
Labels: enhancement

#346 Arreglar tension vacia en F15
  libcnmc/cir_4_2015/F15.py
Labels: error

#348 Mejorar la lectura de la potencia adscrita
  libcnmc/cir_4_2015/F1.py
Labels: error

#349 Mejorar legibilidad del codigo F1 4/2015
  libcnmc/cir_4_2015/F1.py
  libcnmc/utils.py
Labels: enhancement, to be merged

#350 Evitar el reuso de los mismos nombres de variable
  libcnmc/utils.py
Labels: enhancement

#352 Revertir canvios en la generacion del F9 de la 4/2015
  libcnmc/cir_4_2015/F9.py
Labels: error, to be merged

#353 Mejorar la generacion del F10 de la 4/2015
  libcnmc/cir_4_2015/F10AT.py
Labels: enhancement, to be merged

#351 Corregir código de tarifa para 6.1A y 6.1B
  libcnmc/utils.py
Labels: enhancement, to be merged

#355 Fix cel·la tensio retrievment on F15.
  libcnmc/cir_4_2015/F15.py
Labels: error, to be merged

#356 Improve F12Bis 4/2015: Decide which tipus installacio will be included into the file.
  libcnmc/cir_4_2015/F12bis.py
  libcnmc/cli_4_2015.py
Labels: enhancement, to be merged

#354 Exclude FAT in f12bis.
  libcnmc/cir_4_2015/F12bis.py
Labels: enhancement, to be merged

#357 Fix the way that FusAT are excluded.
  libcnmc/cir_4_2015/F12bis.py
Labels: error

#358 Fix codificacion on F10bt for the field o_tipus
  libcnmc/cir_4_2015/F10BT.py
Labels: error, to be merged

#359 Include all tipus inventari on F15.
  libcnmc/cir_4_2015/F15.py
Labels: enhancement, to be merged

#360 Fix x,y initialization.
  libcnmc/cir_4_2015/F15.py
Labels: error, to be merged

#361 Get SRID from res_config instead of use giscegis function
  libcnmc/cir_4_2015/F15.py
Labels: enhancement

#362 Changed the default value for 2l+p i fiabilitat.
  libcnmc/cli_4_2015.py
Labels: error, to be merged

#363 Add options to 4 2015 f13c
  libcnmc/cir_4_2015/F13C.py
  libcnmc/cli_4_2015.py
Labels: enhancement, to be merged

#364 Mejorar la obtencion del nodo
  libcnmc/cir_4_2015/F16.py
Labels: enhancement, to be merged
