Repository gisce/libCNMC, pull requests merged in 2018-03, with the labels that each got.

#305 Add code for tarifa 6.1.A and 6.2.A
  libcnmc/utils.py
Labels: error, to be merged

#306 Add B tarifas (6.x)
  libcnmc/utils.py
Labels: error

#307 Add docstring of get_saturacio
  libcnmc/cir_4_2015/F11.py
Labels: enhancement

#308 Improve docstrings 4/2015
  libcnmc/cir_4_2015/F1.py
Labels: enhancement

#304 Mejorar generacion del F1 y F1bis de la 4/2015
  libcnmc/cir_4_2015/F1.py
Labels: enhancement, to be merged

#309 Only apear F1 with modcons
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F1bis.py
Labels: enhancement

#311 Improve F1 and F1bis from the circular 4/2015: Exclude CUPS where the tarifa is like 'RE'
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F1bis.py
Labels: enhancement, to be merged

#313 Circular 4/2015-F20: Exclude CUPS with tarifa like 'RE'
  libcnmc/cir_4_2015/F20.py
Labels: enhancement, to be merged
