Repository gisce/libCNMC, pull requests merged in 2019-06, with the labels that each got.

#395 F1bis Solo en estado tall activa and baixa
  libcnmc/cir_4_2015/F1bis.py
Labels: improvement

#396 Fix f1 search
  libcnmc/cir_4_2015/F1bis.py
  setup.py
Labels: error

#399 Comprobar x y y de la subestacion
  libcnmc/cir_4_2015/F13.py
Labels: error

#400 Arreglar error tipografico
  libcnmc/cir_4_2015/F13.py
Labels: error

#398 Fix the way that the CUPS are filtered on F1, F1bis, F11 and F20.
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F11.py
  libcnmc/cir_4_2015/F1bis.py
  libcnmc/cir_4_2015/F20.py
Labels: error, improvement, to be merged

#397 Filter the polisses on the F1bis properly
  libcnmc/cir_4_2015/F1bis.py
Labels: error, to be merged

#401 Arreglar la obtencion del nodo en el F1 de la 4/2015
  libcnmc/cir_4_2015/F1.py
Labels: error

#402 Arreglar lectura del node_id del fichero F12
  libcnmc/cir_4_2015/F12.py
Labels: error

#403 Arreglar la escritura del nodo de F15
  libcnmc/cir_4_2015/F15.py
Labels: error

#404 Arreglar F1 al comprobar el nodo
  libcnmc/cir_4_2015/F1.py
Labels: error

#405 Añadida la opción de elección la zona de calidad.
  libcnmc/cir_4_2015/F1.py
  libcnmc/cli_4_2015.py
Labels: improvement

#407 Arreglar datos del tramo en el F15
  libcnmc/cir_4_2015/F15.py
Labels: error

#406 Update the way field "Equipo de Mesura" is calculated on the 4/2015-F1
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F11.py
  libcnmc/cir_4_2015/F1bis.py
  libcnmc/cir_4_2015/F20.py
  libcnmc/cli_4_2015.py
  libcnmc/utils.py
Labels: improvement, to be merged

#408 Simplificar parametros de busqueda
  libcnmc/cir_4_2015/F1.py
Labels: improvement

#409 Eliminar variables sin usar
  libcnmc/res_4666/AUD_FIA.py
Labels: improvement

#410 Read node_id for condensadors
  libcnmc/cir_4_2015/F16.py
Labels: improvement

#411 Rellenar datos de x y y del F1
  libcnmc/cir_4_2015/F1.py
Labels: improvement

#412 Comprovar si raven esta disponible
  libcnmc/cir_4_2015/F1.py
Labels: error

#413 Gestionar cts sin nodo
  libcnmc/utils.py
Labels: improvement

#414 Arreglar escritura del F9 4/2015
  libcnmc/cir_4_2015/F9.py
Labels: error

#415 Force version for pyproj.
  requirements.txt
Labels: error, to be merged

#416 Añadir soprte para el modelo de cuadros BT
  libcnmc/cir_4_2015/F11.py
Labels: improvement

#418 Fix 4/2015-F1 distri code generation.
  libcnmc/cir_4_2015/F1.py
Labels: error, to be merged

#419 Arreglar retrocompatibilidad del fichero F11
  libcnmc/cir_4_2015/F11.py
Labels: error

#421 4/2015-F9: Add elements with data baixa but active.
  libcnmc/cir_4_2015/F11.py
Labels: improvement, to be merged

#420 Add support for field 'geom' on 4/2015: F9
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F11.py
  libcnmc/cir_4_2015/F13.py
  libcnmc/cir_4_2015/F15.py
  libcnmc/cir_4_2015/F16.py
  libcnmc/cir_4_2015/F9.py
  libcnmc/utils.py
Labels: improvement, to be merged

#422 Modificar criterio de busqueda del F12bis
  libcnmc/cir_4_2015/F12bis.py
Labels: improvement

#423 Improve f15 compatibility
  libcnmc/utils.py
Labels: improvement

#424 Fix start and end nodes on 4/2015: F10
  libcnmc/cir_4_2015/F10AT.py
  libcnmc/cir_4_2015/F10BT.py
Labels: error, to be merged

#425 Ensure that each tqdm desc match for each file obj.
  libcnmc/cir_4_2015/F10AT.py
  libcnmc/cir_4_2015/F10BT.py
  libcnmc/cir_4_2015/F12.py
  libcnmc/cir_4_2015/F13.py
  libcnmc/cir_4_2015/F13C.py
  libcnmc/cir_4_2015/F13bis.py
  libcnmc/cir_4_2015/F14.py
  libcnmc/cir_4_2015/F20.py
Labels: improvement, to be merged

#426 Fix the trafo node retrivement.
  libcnmc/cir_4_2015/F12.py
  libcnmc/cir_4_2015/F13bis.py
Labels: error

#427 Improve 4/2015: F15 checking only Cel·les
  libcnmc/cir_4_2015/F15.py
  libcnmc/cir_4_2015/__init__.py
  libcnmc/cli_4_2015.py
Labels: error, to be merged

#428 Fix 4/2015: F1 'get_tipus_connexio' method
  libcnmc/cir_4_2015/F1.py
Labels: error, to be merged
