Repository gisce/libCNMC, pull requests merged in 2019-05, with the labels that each got.

#390 Fix 4 2015
  libcnmc/cli_4_2015.py
Labels: error

#391 Fix on get_edge_id
  libcnmc/res_4666/LBT.py
Labels: improvement

#392 Crear fichero nuevo con información referente a los elementos con estado 1
  libcnmc/cli_4666.py
  libcnmc/core/__init__.py
  libcnmc/res_4666/CTS.py
  libcnmc/res_4666/DES.py
  libcnmc/res_4666/FIA.py
  libcnmc/res_4666/LAT.py
  libcnmc/res_4666/LBT.py
  libcnmc/res_4666/MAQ.py
  libcnmc/res_4666/POS.py
  libcnmc/res_4666/SUB.py
  libcnmc/utils.py
Labels: improvement, to be merged

#393 Usar node_id para el nombre d elos nodos si esta disponible
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F11.py
  libcnmc/cir_4_2015/F12.py
  libcnmc/cir_4_2015/F13bis.py
  libcnmc/cir_4_2015/F15.py
  libcnmc/cir_4_2015/F16.py
  libcnmc/utils.py
  requirements.txt
Labels: improvement, to be merged

#394 Mejorar docstrings
  libcnmc/cir_4_2015/F1bis.py
Labels: improvement
