Repository gisce/libCNMC, pull requests merged in 2020-03, with the labels that each got.

#434 Delete trash code and fix condensadors with -m parameter
  libcnmc/cli_4666.py
Labels: error, to be merged

#435 Fix 4/2015-F9: Ensure that, if it the elements have the column geom, it's filled
  libcnmc/cir_4_2015/F9.py
Labels: error, to be merged

#433 Generación de ficheros de inversiones acorde a la resolución 2019-6181
  libcnmc/audit_6181/CTS.py
  libcnmc/audit_6181/DES.py
  libcnmc/audit_6181/FIA.py
  libcnmc/audit_6181/LAT.py
  libcnmc/audit_6181/LBT.py
  libcnmc/audit_6181/MAQ.py
  libcnmc/audit_6181/POS.py
  libcnmc/audit_6181/SE.py
  libcnmc/audit_6181/__init__.py
  libcnmc/cli.py
  libcnmc/cli_6181.py
  libcnmc/utils.py
Labels: improvement, to be merged

#436 Arreglar condición de salida para fichero modif
  libcnmc/core/__init__.py
  libcnmc/res_4666/LBT.py
Labels: error, improvement, to be merged

#437 Add 'Motivaciones' to the investments report
  libcnmc/audit_6181/CTS.py
  libcnmc/audit_6181/DES.py
  libcnmc/audit_6181/FIA.py
  libcnmc/audit_6181/LAT.py
  libcnmc/audit_6181/LBT.py
  libcnmc/audit_6181/MAQ.py
  libcnmc/audit_6181/POS.py
  libcnmc/audit_6181/SE.py
  libcnmc/cli_6181.py
  libcnmc/core/__init__.py
  libcnmc/utils.py
Labels: improvement, to be merged

#438 Arreglar formato en algunos ficheros de la resolucion 6181
  libcnmc/audit_6181/CTS.py
  libcnmc/audit_6181/DES.py
  libcnmc/audit_6181/FIA.py
  libcnmc/audit_6181/LAT.py
  libcnmc/audit_6181/LBT.py
  libcnmc/audit_6181/MAQ.py
  libcnmc/audit_6181/POS.py
  libcnmc/audit_6181/SE.py
  libcnmc/cli_6181.py
  libcnmc/utils.py
Labels: error, to be merged
