Repository gisce/libCNMC, pull requests merged in 2023-02, with the labels that each got.

#467 CI - check if bump commit
  .github/workflows/version.yml
Labels: patch

#468 IMP Mejoras en MODELO - B1 y POTENCIA_ADSCRITA - A1
  libcnmc/cir_8_2021/FA1.py
  libcnmc/cir_8_2021/FB1.py
Labels: improvement, minor

#469 IMP A1 Obtener el último autoconsumo_id del año
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#470 ADD Filtro de ids en get_sequence según criteri_regulatori, B3.2 y B4
  libcnmc/cir_8_2021/FB3_2.py
  libcnmc/cir_8_2021/FB4.py
Labels: minor

#472 IMP Lee los campos energia_autoconsumida y energia_excedentaria de CUPS para el A1
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#473 IMP Mejora el filtro de las polizas en el A1 para que se comporte como el F1 Cir. 4/2015
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#475 FIX Convierte un punto tipo str a float por compatibilidad con Shapely - B1.1 Cir8/2021
  libcnmc/cir_8_2021/FB1_1.py
Labels: patch

#474 ADD Añade la generación del formulario C2 - Cir8/2021
  libcnmc/cir_8_2021/FC2.py
  libcnmc/cir_8_2021/__init__.py
  libcnmc/cli_8_2021.py
  libcnmc/utils.py
Labels: minor

#476 IMP Eliminar el formulario B5.2 ya que se encontraba erróneamente en el código - Cir8/2021
  libcnmc/cir_8_2021/FB5_2.py
  libcnmc/cir_8_2021/__init__.py
  libcnmc/cli_8_2021.py
Labels: patch

#478 Pasar la generació de los ficheros de la 4666 a StopMultiprocess
  libcnmc/res_4666/AUD_CTS.py
  libcnmc/res_4666/AUD_FIA.py
  libcnmc/res_4666/AUD_LAT.py
  libcnmc/res_4666/AUD_LBT.py
  libcnmc/res_4666/AUD_POS.py
  libcnmc/res_4666/CON.py
  libcnmc/res_4666/CTS.py
  libcnmc/res_4666/DES.py
  libcnmc/res_4666/FIA.py
  libcnmc/res_4666/LAT.py
  libcnmc/res_4666/LBT.py
  libcnmc/res_4666/MAQ.py
  libcnmc/res_4666/MOD.py
  libcnmc/res_4666/POS.py
  libcnmc/res_4666/SUB.py
Labels: minor

#477 Ignore pubsub always
  libcnmc/core/backend.py
Labels: patch

#480 FIX Mejora el cálculo de estado_contrato en el A1 - Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#482 FIX Corrige los parametros de un search del A1
  libcnmc/cir_8_2021/FA1.py
Labels: error, patch

#483 FIX Resuelve la generación del A1, campo estado_contrato - Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#485 FIX Resuelve errores de funcionamiento debido al límite del search, A1 - Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#486 Convert 4/2015 to StopMultiprocess
  libcnmc/cir_4_2015/F1.py
  libcnmc/cir_4_2015/F10AT.py
  libcnmc/cir_4_2015/F10BT.py
  libcnmc/cir_4_2015/F11.py
  libcnmc/cir_4_2015/F12.py
  libcnmc/cir_4_2015/F12bis.py
  libcnmc/cir_4_2015/F13.py
  libcnmc/cir_4_2015/F13C.py
  libcnmc/cir_4_2015/F13bis.py
  libcnmc/cir_4_2015/F14.py
  libcnmc/cir_4_2015/F15.py
  libcnmc/cir_4_2015/F16.py
  libcnmc/cir_4_2015/F1bis.py
  libcnmc/cir_4_2015/F20.py
  libcnmc/cir_4_2015/F9.py
Labels: minor

#487 Migrate D2 case tracking to mongoDB
  libcnmc/cir_8_2021/FD2.py
Labels: patch

#488 FIX Rectifica el nombre de una variable A1 - Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#489 Fixing writing
  libcnmc/core/__init__.py
Labels: patch

#490 Fix task done on break
  libcnmc/core/__init__.py
Labels: patch

#491 IMP Mejoras en A1
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#492 IMP Filtra las pólizas canceladas en el campo BAJA_SUMINISTRO A1- Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#493 FIX Inicializa potencia_adscrita a 0 - A1 - Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#494 IMP Ajustes en diversos formularios - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2_1.py
  libcnmc/cir_8_2021/FB2_2.py
  libcnmc/cir_8_2021/FB3.py
  libcnmc/cir_8_2021/FB4.py
Labels: minor

#495 IMP Fuerza el valor abosulto del campo ENERGIA_EXCEDENTARIA - Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#496 FIX Cambia la magnitud de la tension en el comparador campo ESTADO - B1 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: patch
