Repository gisce/libCNMC, pull requests merged in 2023-05, with the labels that each got.

#523 Correcciones en el trato de los rechazos de b104 - Circular 8/2021 - FD2
  libcnmc/cir_8_2021/FD2.py
Labels: patch

#531 FIX Lectura del campo punto forntera en AT - B1 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: patch

#532 IMP El campo FINANCIADO se lee directamente de los modelos de AT, BT y CTs - Cir 8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
Labels: minor

#533 IMP OPERACION vacío cuando MODELO = M - B1 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: patch

#534 IMP OPERACION vacío cuando MODELO = M - B1 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: patch

#535 IMP REACTANCIA, RESISTENCIA Y INTENSIDAD = 0,001 si son < 0.001 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: minor

#537 FIX Corrige la lectura de la potencia contractada en el A1 - Cir8/2021
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#539 Afegim el formulari D1 de la Circular 8/2021
  libcnmc/cir_8_2021/FD1.py
  libcnmc/cir_8_2021/__init__.py
  libcnmc/cli_8_2021.py
  libcnmc/utils.py
Labels: minor

#538 Añadir formulario C6 en la libCNMC
  libcnmc/cir_8_2021/FC6.py
  libcnmc/cir_8_2021/__init__.py
  libcnmc/cli_8_2021.py
  libcnmc/utils.py
Labels: improvement, to be merged, minor

#541 IMP Cambia el nombre interno de los ficheros para corregir el nombre del fichero final generado - Cir8/2021
  libcnmc/utils.py
Labels: patch

#542 Add .model() to XML-RPC
  libcnmc/core/backend.py
Labels: improvement, minor

#543 Corrección D1
  libcnmc/cir_8_2021/FD1.py
Labels: error, patch

#544 Revert "IMP Cambia el nombre interno de los ficheros para corregir el nombre del fichero final generado - Cir8/2021"
  libcnmc/utils.py
Labels: patch

#545 IMP Añade la generación del formulario C2
  libcnmc/cir_8_2021/FC2.py
Labels: minor

#546 IMP Corrige la lectura de las líneas asociadas a un soporte B6 - Cir8/2021
  libcnmc/cir_8_2021/FB6.py
Labels: minor

#547 IMP Modifica el sequence del B1 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: minor

#548 Fix provincia, municipi D1
  libcnmc/cir_8_2021/FD1.py
Labels: patch

#549 IMP MOTIVACION y TIPO_INVERSIÓN vacío cuando hay FECHA_BAJA
  libcnmc/cir_8_2021/FB1.py
Labels: patch

#550 IMP CAU vacío si COD_AUTO in '002', '003', '005', '007'
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#551 IMP Modifica el comportamiento del campo ESTADO
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
  libcnmc/cir_8_2021/FB8.py
Labels: minor

#552 IMP '0,000' cuando el valor es '0' para cumplir con el validador Cir8/2021
  libcnmc/cir_8_2021/FA5.py
Labels: patch

#553 IMP Busca celdas de baja al buscar la máquina - Cir8/2021
  libcnmc/cir_8_2021/FB2_2.py
Labels: patch

#555 IMP Corrige la lectura del campo Municipio B6 - Cir8/2021
  libcnmc/cir_8_2021/FB6.py
Labels: minor

#556 IMP Formato en FINANCIADO B2
  libcnmc/cir_8_2021/FB2.py
Labels: patch

#554 Add Formulario F1 Circular 8/2021
  libcnmc/cir_8_2021/FF1.py
  libcnmc/cir_8_2021/__init__.py
  libcnmc/cli_8_2021.py
  libcnmc/utils.py
Labels: minor

#558 IMP Deciamles de FINANCIADO en B1 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: patch

#560 IMP Filtro de criterio regulatorio en B1.1 - Cir8/2021
  libcnmc/cir_8_2021/FB1_1.py
Labels: minor

#561 IMP Coordenada Z a '0,000' - Cir 8/2021
  libcnmc/cir_8_2021/FA1.py
  libcnmc/cir_8_2021/FA2.py
  libcnmc/cir_8_2021/FA3.py
  libcnmc/cir_8_2021/FB1_1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB3.py
  libcnmc/cir_8_2021/FB3_1.py
  libcnmc/cir_8_2021/FB6.py
  libcnmc/cir_8_2021/FB7.py
Labels: minor

#562 FIX Corrige el campo FINANCIADO cuando es 0 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
Labels: minor

#564 Añadir formulario C1 en la libCNMC
  libcnmc/cir_8_2021/FC1.py
  libcnmc/cir_8_2021/__init__.py
  libcnmc/cli_8_2021.py
  libcnmc/utils.py
Labels: improvement, to be merged, minor

#566 Utilizar el nombre del tramo para el código de segmento para el fichero B1.1
  libcnmc/cir_8_2021/FB1_1.py
Labels: patch

#567 Add c3 c4 from
  libcnmc/cir_8_2021/FC3.py
  libcnmc/cir_8_2021/FC4.py
  libcnmc/cir_8_2021/__init__.py
  libcnmc/cli_8_2021.py
  libcnmc/utils.py
Labels: to be merged, minor

#568 IMP Modifica el comportamiento de TIPO_INVERSION y OPERACION según el valdiador - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB2_1.py
  libcnmc/cir_8_2021/FB3_3.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
Labels: minor

#570 IMP Potencia con 3 decimales D1 - Cir8/2021
  libcnmc/cir_8_2021/FD1.py
Labels: patch

#571 IMP Fuerza NUDO_BAJA = NUDO_ALTA según CINI - Cir8/2021
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB5.py
Labels: minor
