Repository gisce/libCNMC, pull requests merged in 2023-06, with the labels that each got.

#572 IMP Mejoras varias en el fichero B9 - Cir8/2021
  libcnmc/cir_8_2021/FB9.py
Labels: minor

#573 FIX Corrige el sequence del B1.1 - Cir8/2021
  libcnmc/cir_8_2021/FB1_1.py
Labels: patch

#574 IMP Mejora el filtro de obras cuando hay más de una obra asociada - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
  libcnmc/cir_8_2021/FB8.py
Labels: minor

#575 FIX Código CCAA
  libcnmc/cir_8_2021/FC1.py
Labels: error, to be merged, patch

#576 IMP Añade campos al importador de CUPS.csv
  libcnmc/core/__init__.py
Labels: minor

#577 IMP OPERACION vacío si MODELO=M - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
Labels: patch

#578 IMP TIPO_INVERSION vacío si hay FECHA_BAJA - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
Labels: minor

#580 IMP Quita las referencias en el B9 - Cir8/2021
  libcnmc/cir_8_2021/FB9.py
Labels: patch

#581 IMP Vacía el valor de las subenciones PRTR para el ejercicio 2022 - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
  libcnmc/cir_8_2021/FB8.py
Labels: patch

#582 IMP Filtra solo los registros con tipo de inversión B9 - Cir8/2021
  libcnmc/cir_8_2021/FB9.py
Labels: patch

#584 UpdateFile migrated to StopMultiprocess
  libcnmc/core/__init__.py
Labels: patch

#579 Crear logs sobre los casos ATC por defecto y filtrar por subtipo los R1 utilizados Circular 8/2021 - FD2
  libcnmc/cir_8_2021/FD2.py
Labels: minor

#585 IMP
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
Labels: minor

#587 FIX Versión de Python
  .github/workflows/release.yml
Labels: patch

#589 IMP Lee directamente los valores x y del A3 - Cir8/2021
  libcnmc/cir_8_2021/FA3.py
Labels: patch

#591 IMP Borra atributos innecesarios del modelo CNMC
  libcnmc/models/cnmcmodel.py
Labels: patch

#592 IMP Segmento a 22 carácteres B1.1. - Cir 8/2021
  libcnmc/cir_8_2021/FB1_1.py
Labels: patch

#593 IMP TIPO_INVERSION = 0 y ESTADO = 1 si MODELO = M - Cir8/2021
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
Labels: minor

#594 IMP Protege IDENTIFICADOR si se introduce manualmente un registro y no se rellena C3 - Cir8/2021
  libcnmc/cir_8_2021/FC3.py
Labels: patch
