Repository gisce/libCNMC, pull requests merged in 2023-01, with the labels that each got.

#457 Fix exit with token based
  libcnmc/cir_8_2021/FA1.py
  libcnmc/cir_8_2021/FA2.py
  libcnmc/cir_8_2021/FA3.py
  libcnmc/cir_8_2021/FA4.py
  libcnmc/cir_8_2021/FA5.py
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB1_1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB2_1.py
  libcnmc/cir_8_2021/FB2_2.py
  libcnmc/cir_8_2021/FB3.py
  libcnmc/cir_8_2021/FB3_1.py
  libcnmc/cir_8_2021/FB3_2.py
  libcnmc/cir_8_2021/FB3_3.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB5_2.py
  libcnmc/cir_8_2021/FB6.py
  libcnmc/cir_8_2021/FB7.py
  libcnmc/cir_8_2021/FB8.py
  libcnmc/cir_8_2021/FB9.py
  libcnmc/cir_8_2021/FD2.py
  libcnmc/core/__init__.py
Labels: error, to be merged

#458 ADD Lee las energias en A5 y resuelve errores
  libcnmc/cir_8_2021/FA5.py
Labels: improvement

#459 Auto tag ci
  .github/workflows/version.yml
Labels: patch

#460 add bump config file
  .bumpversion.cfg
Labels: patch

#461 add git config ci
  .github/workflows/version.yml
Labels: patch

#462 fix version type ci
  .github/workflows/version.yml
Labels: patch

#463 add ssh ci
  .github/workflows/version.yml
Labels: patch

#464 ci email
  .github/workflows/version.yml
Labels: patch

#466 try with ssh-key checkout
  .github/workflows/version.yml
Labels: patch
