Repository gisce/libCNMC, pull requests merged in 2024-06, with the labels that each got.

#654 Exportar unicamente datos de el año actual en Z8_01
  libcnmc/cir_8_2021/FD2.py
Labels: to be merged, patch

#655 ADD Cobertura para el nuevo campo de tension entrante en CT en B2
  libcnmc/cir_8_2021/FB2.py
Labels: improvement, to be merged, minor

#656 FIX parseo fecha para aceptar recibir tipo timestamp o fecha en B2
  libcnmc/cir_8_2021/FB2.py
Labels: error, to be merged, patch

#657 Update requirements for py3
  requirements.txt
Labels: patch
