Repository gisce/libCNMC, pull requests merged in 2024-07, with the labels that each got.

#658 FIX valor residual de cero a vacio
  libcnmc/cir_8_2021/FB4.py
Labels: error, to be merged, patch

#659 FIX valores coordenadas X e Y transformadas a SRID 25830
  libcnmc/cir_8_2021/FA3.py
Labels: error, to be merged, patch

#660 FIX Calculo conceptos 5_G_8 y 5_G_9 del B9
  libcnmc/cir_8_2021/FB9.py
Labels: error, to be merged, patch

#661 IMP excluir de los ids a consumir las bajas de modelo M
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB6.py
Labels: improvement, to be merged, minor

#663 FIX pasar de V a kV con el nuevo campo tensio_entrant
  libcnmc/cir_8_2021/FB2.py
Labels: error, patch

#665 FIX llamada a funcion para inactivos usando context A2
  libcnmc/cir_8_2021/FA2.py
Labels: error, patch

#664 A1: Opcion para extraer la tension del contrato
  libcnmc/cir_8_2021/FA1.py
  libcnmc/cli_8_2021.py
Labels: improvement, minor, deployed PRE

#666 FIX valor 2 en A2 para autoconsumos colectivos
  libcnmc/cir_8_2021/FA2.py
Labels: error, to be merged, patch, bug

#667 A2: FIX los valores de las energias en decimales con coma
  libcnmc/cir_8_2021/FA2.py
Labels: error, to be merged, bug

#668 A2: FIX valores de tension en kV
  libcnmc/cir_8_2021/FA2.py
Labels: error, to be merged, patch, bug

#669 B9: IMP Filtrar datos por modelo igual a 'I':Inventario)
  libcnmc/cir_8_2021/FB9.py
Labels: improvement, to be merged, patch
