Repository gisce/libCNMC, pull requests merged in 2024-04, with the labels that each got.

#639 A1: Millorem el càlcul de la potencia adscrita
  libcnmc/cir_8_2021/FA1.py
Labels: minor

#640 B2.2: Se añade el filtro que no sean del tipo FUS_AT
  libcnmc/cir_8_2021/FB2_2.py
Labels: patch

#641 A1: Arreglar si no tienen boletín no falle
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#642 A1: Eliminar vaciar CAU si COD_AUTO '002', '003', '005', '007'
  libcnmc/cir_8_2021/FA1.py
Labels: patch

#643 B2.2: Se utiliza la trazabilidad si existe el campo
  libcnmc/cir_8_2021/FB2_2.py
Labels: minor

#645 FD2: Se exportaban los datos sin distinguir por año
  libcnmc/cir_8_2021/FD2.py
Labels: error, to be merged, patch

#646 A1: Mejora tipos de conexión en CONTA-AT
  libcnmc/utils.py
Labels: patch
