Repository gisce/libCNMC, pull requests merged in 2025-07, with the labels that each got.

#694 Vincular estado a modelos E para tipo inversion
  libcnmc/cir_8_2021/FB1.py
  libcnmc/cir_8_2021/FB2.py
  libcnmc/cir_8_2021/FB4.py
  libcnmc/cir_8_2021/FB5.py
  libcnmc/cir_8_2021/FB6.py
Labels: improvement, to be merged (GIS), patch

#698 Arreglo fecha de baja en trabajo ct para B2
  libcnmc/cir_8_2021/FB2.py
Labels: to be merged (GIS), deployed, patch, bug

#699 Descartar el filtro de fecha de creación en los CUPS
  libcnmc/cir_8_2021/FA1.py
Labels: to be merged (GIS), patch, bug
